// Copyright 2025 The goREgo Authors. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/execution/worker_protocol/worker_protocol.proto

package worker_protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// An input file for a work request.
type Input struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The path in the file system where to read this input artifact from.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// A hash-value of the contents. The format of the contents is unspecified and
	// the digest should be treated as an opaque token.
	Digest        []byte `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Input) Reset() {
	*x = Input{}
	mi := &file_pkg_execution_worker_protocol_worker_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input) ProtoMessage() {}

func (x *Input) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_execution_worker_protocol_worker_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input.ProtoReflect.Descriptor instead.
func (*Input) Descriptor() ([]byte, []int) {
	return file_pkg_execution_worker_protocol_worker_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *Input) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Input) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

// A single work unit sent to a persistent worker process.
// Matches the Bazel persistent worker wire protocol.
type WorkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Command-line arguments for the work unit.
	Arguments []string `protobuf:"bytes,1,rep,name=arguments,proto3" json:"arguments,omitempty"`
	// The inputs that the worker is allowed to read during execution.
	Inputs []*Input `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty"`
	// Unique request identifier. 0 means singleplex (one request at a time).
	RequestId int32 `protobuf:"varint,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// When true, this is a cancel request for a previously sent WorkRequest
	// with the same request_id.
	Cancel bool `protobuf:"varint,4,opt,name=cancel,proto3" json:"cancel,omitempty"`
	// Verbosity level. Greater than 0 enables extra debug output.
	Verbosity int32 `protobuf:"varint,5,opt,name=verbosity,proto3" json:"verbosity,omitempty"`
	// The relative directory inside the worker's working directory where inputs
	// and outputs are placed, for sandboxing purposes.
	SandboxDir    string `protobuf:"bytes,6,opt,name=sandbox_dir,json=sandboxDir,proto3" json:"sandbox_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkRequest) Reset() {
	*x = WorkRequest{}
	mi := &file_pkg_execution_worker_protocol_worker_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkRequest) ProtoMessage() {}

func (x *WorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_execution_worker_protocol_worker_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkRequest.ProtoReflect.Descriptor instead.
func (*WorkRequest) Descriptor() ([]byte, []int) {
	return file_pkg_execution_worker_protocol_worker_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *WorkRequest) GetArguments() []string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *WorkRequest) GetInputs() []*Input {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *WorkRequest) GetRequestId() int32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *WorkRequest) GetCancel() bool {
	if x != nil {
		return x.Cancel
	}
	return false
}

func (x *WorkRequest) GetVerbosity() int32 {
	if x != nil {
		return x.Verbosity
	}
	return 0
}

func (x *WorkRequest) GetSandboxDir() string {
	if x != nil {
		return x.SandboxDir
	}
	return ""
}

// Response from a persistent worker process after completing a work unit.
// Matches the Bazel persistent worker wire protocol.
type WorkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exit code of the work unit. 0 means success.
	ExitCode int32 `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// Combined stdout/stderr output from the work unit.
	Output string `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	// Must match the request_id of the WorkRequest this is a response to.
	RequestId int32 `protobuf:"varint,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// When true, indicates the request was cancelled.
	WasCancelled  bool `protobuf:"varint,4,opt,name=was_cancelled,json=wasCancelled,proto3" json:"was_cancelled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkResponse) Reset() {
	*x = WorkResponse{}
	mi := &file_pkg_execution_worker_protocol_worker_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkResponse) ProtoMessage() {}

func (x *WorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_execution_worker_protocol_worker_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkResponse.ProtoReflect.Descriptor instead.
func (*WorkResponse) Descriptor() ([]byte, []int) {
	return file_pkg_execution_worker_protocol_worker_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *WorkResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *WorkResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *WorkResponse) GetRequestId() int32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *WorkResponse) GetWasCancelled() bool {
	if x != nil {
		return x.WasCancelled
	}
	return false
}

var File_pkg_execution_worker_protocol_worker_protocol_proto protoreflect.FileDescriptor

const file_pkg_execution_worker_protocol_worker_protocol_proto_rawDesc = "" +
	"\n" +
	"3pkg/execution/worker_protocol/worker_protocol.proto\x12\x0fworker_protocol\"3\n" +
	"\x05Input\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\fR\x06digest\"\xd1\x01\n" +
	"\vWorkRequest\x12\x1c\n" +
	"\targuments\x18\x01 \x03(\tR\targuments\x12.\n" +
	"\x06inputs\x18\x02 \x03(\v2\x16.worker_protocol.InputR\x06inputs\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\x05R\trequestId\x12\x16\n" +
	"\x06cancel\x18\x04 \x01(\bR\x06cancel\x12\x1c\n" +
	"\tverbosity\x18\x05 \x01(\x05R\tverbosity\x12\x1f\n" +
	"\vsandbox_dir\x18\x06 \x01(\tR\n" +
	"sandboxDir\"\x87\x01\n" +
	"\fWorkResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\x05R\trequestId\x12#\n" +
	"\rwas_cancelled\x18\x04 \x01(\bR\fwasCancelledB>Z<github.com/colinrgodsey/goREgo/pkg/execution/worker_protocolb\x06proto3"

var (
	file_pkg_execution_worker_protocol_worker_protocol_proto_rawDescOnce sync.Once
	file_pkg_execution_worker_protocol_worker_protocol_proto_rawDescData []byte
)

func file_pkg_execution_worker_protocol_worker_protocol_proto_rawDescGZIP() []byte {
	file_pkg_execution_worker_protocol_worker_protocol_proto_rawDescOnce.Do(func() {
		file_pkg_execution_worker_protocol_worker_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_execution_worker_protocol_worker_protocol_proto_rawDesc), len(file_pkg_execution_worker_protocol_worker_protocol_proto_rawDesc)))
	})
	return file_pkg_execution_worker_protocol_worker_protocol_proto_rawDescData
}

var file_pkg_execution_worker_protocol_worker_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_execution_worker_protocol_worker_protocol_proto_goTypes = []any{
	(*Input)(nil),        // 0: worker_protocol.Input
	(*WorkRequest)(nil),  // 1: worker_protocol.WorkRequest
	(*WorkResponse)(nil), // 2: worker_protocol.WorkResponse
}
var file_pkg_execution_worker_protocol_worker_protocol_proto_depIdxs = []int32{
	0, // 0: worker_protocol.WorkRequest.inputs:type_name -> worker_protocol.Input
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_execution_worker_protocol_worker_protocol_proto_init() }
func file_pkg_execution_worker_protocol_worker_protocol_proto_init() {
	if File_pkg_execution_worker_protocol_worker_protocol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_execution_worker_protocol_worker_protocol_proto_rawDesc), len(file_pkg_execution_worker_protocol_worker_protocol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_execution_worker_protocol_worker_protocol_proto_goTypes,
		DependencyIndexes: file_pkg_execution_worker_protocol_worker_protocol_proto_depIdxs,
		MessageInfos:      file_pkg_execution_worker_protocol_worker_protocol_proto_msgTypes,
	}.Build()
	File_pkg_execution_worker_protocol_worker_protocol_proto = out.File
	file_pkg_execution_worker_protocol_worker_protocol_proto_goTypes = nil
	file_pkg_execution_worker_protocol_worker_protocol_proto_depIdxs = nil
}
